### ISSUE TITLE
uberserver opens to many mysql connections

### ISSUE THREAD

**Issue by abma** [lunixbochs/uberserver#14]
currently it has ~220 connections open... that should be reduced. at max 5 should be imo enough.

->website currently isn't working

**Comment by lunixbochs** [comment]
It really shouldn't. Might be a function of someone reloading the server far too much :) I'd recommend restarting it and getting mad at whoever reloads it most.

## 

Ryan Hileman

**Comment by abma** [comment]
"it" ?

the python process has ~220 connections open... restarting apache didn't change anything. also, i don't know how to restart the lobby server without fears of data-loss...

**Comment by lunixbochs** [comment]
it = uberserver. I should hope that was obvious from context :P

## 

Ryan Hileman

**Comment by abma** [comment]
"it shouldn't" <- then wtf? it HAS ~220 connection open...

**Comment by abma** [comment]
oops, my grep was wrong. but it still has about 40 connections open to the mysql server ... sorry i'm tired :-/

**Comment by lunixbochs** [comment]
"Might be a function of someone reloading the server far too much" - the RELOAD command - something people have been using despite my recommendation "don't use this very much / ever without talking to me"

The sql class has a connection pool size of _root.max_threads \* 2. max_threads defaults to 25. It's safe to reduce max_threads to 1 (cli flag --maxthreads, m) because we use event dispatching now instead of threads.

**Comment by abma** [comment]
oh, i suck today... you're right and meh.. then still the cause is unknown why the mysql server sucks. maybe the zero-k.info website is the cause...

sorry! and thanks for the quick response.
