### ISSUE TITLE
data loss (user accounts)

### ISSUE THREAD

**Issue by abma** [lunixbochs/uberserver#6]
i guess its because of a non-gracefully restart

for example see:
http://springrts.com/phpbb/viewtopic.php?f=11&t=26593&p=497144

also the .txt file for storing accounts should be abandoned , use a database!

**Comment by lunixbochs** [comment]
it's because the IO performance on the server degrades so badly.

database functionality is already working (it was originally designed without direct accounts.txt support, which was only added to ease transitions), but a database won't be used as long as it's on the current physical server (the source of these problems...)

I need to build a simple proxy and get the lobby authors to change their primary server hostname before I feel comfortable migrating the lobby to my own dedicated server without these IO problems.

**Comment by abma** [comment]
can you switch to mysql on the current server?

at the last restart yesterday, licho had some problems, because some user-accounts disappeared... (it was a clean restart!)

it looked like only very old accounts worked / only accounts that where not active at the time of the reboot.

all these problems are imo because of the plain textfile.

**Comment by lunixbochs** [comment]
dusting off the migration script.

**Comment by abma** [comment]
any news?

**Comment by lunixbochs** [comment]
80f7688

**Comment by abma** [comment]
fixed in my repo: https://github.com/spring/uberserver/commits/master

main server runs now with sql as backend.
